name = "Incertus"
uuid = "747446ac-7ce9-4c8c-bea8-04a4a881d946"
authors = ["Yevgen Ryeznik <yevgen.ryeznik@gmail.com>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
